platform :ios, '11.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

def shared_pods
    pod 'SnapKit', '4.2.0'
end

target 'ScrollStack_Example' do
    pod 'ScrollStack', :path => '../'
    shared_pods
end

target 'ScrollStack_Tests' do
    pod 'ScrollStack', :path => '../'
    shared_pods
end
